### ISSUE TITLE
Undefined offset: 1 in HoneybadgerContext.php line 46

### ISSUE THREAD

**Issue by drbyte** [honeybadger-io/honeybadger-laravel#36]
New error, after updating to 1.7.1

```
HoneybadgerContext.php  46 handleError(8, "Undefined offset: 1", 
"/vendor/honeybadger-io/honeybadger-laravel/src/Middleware/HoneybadgerContext.php", 46)
```

See rest of context in #34 and
https://github.com/honeybadger-io/honeybadger-laravel/pull/35/files#r321220902

**Comment by sixlive** [comment]
UGH. Give me an hour

**Comment by bakerkretzmar** [comment]
In case it helps, for me this appears to be caused by having a route pointed at an invokable controller. [This line](https://github.com/honeybadger-io/honeybadger-laravel/pull/35/files#diff-74f62d52133150a1a21289b53c0e3b37R44) breaks things because the route action name is just `App\Http\Controllers\HomeController`, there's no `@` in it.

**Comment by sixlive** [comment]
I was assuming that was a problem. I'm about to push the patch

**Comment by sixlive** [comment]
Have a fix here https://github.com/honeybadger-io/honeybadger-laravel/pull/37. Waiting on CI, will tag shortly
